[2025-07-25T03:48:53.900+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.fetch_infectious_data scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T03:48:53.916+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.fetch_infectious_data scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T03:48:53.918+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-25T03:48:53.940+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_infectious_data> on 2025-07-24 00:00:00+00:00
[2025-07-25T03:48:53.947+0000] {standard_task_runner.py:60} INFO - Started process 270 to run task
[2025-07-25T03:48:53.954+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'fetch_infectious_data', 'scheduled__2025-07-24T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp8yjfkwew']
[2025-07-25T03:48:53.958+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask fetch_infectious_data
[2025-07-25T03:48:54.064+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.fetch_infectious_data scheduled__2025-07-24T00:00:00+00:00 [running]> on host e76f205e7324
[2025-07-25T03:48:54.226+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ingrid' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='fetch_infectious_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T00:00:00+00:00'
[2025-07-25T03:48:55.124+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-25T03:48:55.147+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=fetch_infectious_data, execution_date=20250724T000000, start_date=20250725T034853, end_date=20250725T034855
[2025-07-25T03:48:55.212+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-25T03:48:55.279+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
