[2025-07-25T03:48:50.232+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.fetch_people_in_space scheduled__2025-07-23T00:00:00+00:00 [queued]>
[2025-07-25T03:48:50.247+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.fetch_people_in_space scheduled__2025-07-23T00:00:00+00:00 [queued]>
[2025-07-25T03:48:50.249+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-25T03:48:50.270+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_people_in_space> on 2025-07-23 00:00:00+00:00
[2025-07-25T03:48:50.277+0000] {standard_task_runner.py:60} INFO - Started process 260 to run task
[2025-07-25T03:48:50.288+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'fetch_people_in_space', 'scheduled__2025-07-23T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpq2jtdn6a']
[2025-07-25T03:48:50.292+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask fetch_people_in_space
[2025-07-25T03:48:50.400+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.fetch_people_in_space scheduled__2025-07-23T00:00:00+00:00 [running]> on host e76f205e7324
[2025-07-25T03:48:50.537+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ingrid' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='fetch_people_in_space' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-23T00:00:00+00:00'
[2025-07-25T03:48:50.872+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-25T03:48:50.888+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=fetch_people_in_space, execution_date=20250723T000000, start_date=20250725T034850, end_date=20250725T034850
[2025-07-25T03:48:50.938+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-25T03:48:50.973+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
